;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ball.Color.Black",DevComment="")
+GameplayTagList=(Tag="Ball.Color.Blue",DevComment="")
+GameplayTagList=(Tag="Ball.Color.Orange",DevComment="")
+GameplayTagList=(Tag="Ball.Color.Red",DevComment="")
+GameplayTagList=(Tag="Ball.Type.Basic",DevComment="")
+GameplayTagList=(Tag="Ball.Upgrade.Shiny",DevComment="")
+GameplayTagList=(Tag="Ball.Upgrade.Signed",DevComment="")
+GameplayTagList=(Tag="Ball.Upgrade.Splitter",DevComment="")
+GameplayTagList=(Tag="Effect.Physics",DevComment="")
+GameplayTagList=(Tag="Effect.Score",DevComment="")
+GameplayTagList=(Tag="Effect.Shop",DevComment="")
+GameplayTagList=(Tag="Effect.WinLoss",DevComment="")
+GameplayTagList=(Tag="Perk.Rarity.Common",DevComment="")
+GameplayTagList=(Tag="Perk.Rarity.Legendary",DevComment="")
+GameplayTagList=(Tag="Perk.Rarity.Rare",DevComment="")
+GameplayTagList=(Tag="Perk.Rarity.Uncommon",DevComment="")
+GameplayTagList=(Tag="Pin.Type.Golden",DevComment="")
+GameplayTagList=(Tag="Pin.Type.Heavy",DevComment="")
+GameplayTagList=(Tag="Pin.Type.Normal",DevComment="")

